---
driver:
  name: docker

        
platforms:
  - name: centos
    driver:
      image_id: bac949ce964b

provisioner:
  name: chef_solo

suites:
  - name: default
    run_list:
      - recipe[django::default]
    attributes:
