# .kitchen.yml

---
driver:
  name: docker


platforms:
  - name: centos
    driver:
      image_id: bac949ce964b

provisioner:
  name: chef_solo

suites:
  - name: source
    run_list:
      - recipe[django::default]
    attributes:
      vim:
        install_method: "source"
  - name: package
    run_list:
      - recipe[django::default]
    attributes:
      vim:
        install_method: "package"
